spring:
  application:
    name: spring-cloud-eureka
  boot:
    admin:
      client:
        url: http://localhost:7001

server:
  #设置Web容器端口号
  port: 7000
  tomcat:
    #表示配置tomcat请求编码
    uri-encoding: UTF-8

#Eureka 相关配置
eureka:
  instance:
    hostname: localhost
  client:
    # 是否把自己作为服务注册到其他服务注册中心：否
    register-with-eureka: false
    # 是否从其他的服务中心同步服务列表：否
    fetch-registry: false
    eureka-server-connect-timeout-seconds: 5
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/