spring:
  application:
    name: zipkin-server
  profiles:
    include: shared
  # zipkin 本身并不发送span
  zipkin:
    enabled: false

server:
  #设置Web容器端口号
  port: 9411
  tomcat:
    #表示配置tomcat请求编码
    uri-encoding: UTF-8

#Eureka 相关配置
eureka:
  client:
    # 是否把自己作为服务注册到其他服务注册中心
    service-url:
      defaultZone: http://localhost:7000/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    # 把ip地址注册到Eureka服务中
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒，如果要迅速获取服务注册状态，可以缩小该值
    lease-renewal-interval-in-seconds: 15
    # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
    # 默认为90秒
    # 如果该值太大，则很可能将流量转发过去的时候，该instance已经不存活了。
    # 如果该值设置太小了，则instance则很可能因为临时的网络抖动而被摘除掉。
    # 该值至少应该大于 leaseRenewalIntervalInSeconds
    lease-expiration-duration-in-seconds: 45

management:
  endpoints:
    web:
      exposure:
        exclude:
          include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false